[package]
name = "mars-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
glam.workspace = true
hashbrown.workspace = true
parking_lot.workspace = true
smallvec.workspace = true
serde.workspace = true