[package]
name = "mars-window"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mars-foundation = { path = "../mars-foundation" }
winit = { workspace = true }
crossbeam = { workspace = true }