[package]
name = "mars-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
anyhow.workspace = true
tracing.workspace = true
rodio = { workspace = true, optional = false }
cpal  = { workspace = true, optional = false }