[package]
name = "mars-asset"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
ron.workspace = true
notify.workspace = true
parking_lot.workspace = true